export const SLICE_PHASES = [
    'PROPOSED',
    'ADMITTED',
    'RUNNING',
    'WORKER_STOPPED',
    'ATTEMPT_FAILED',
    'SCOPE_BLOCKED',
    'SCOPE_AUDIT',
    'VERIFYING',
    'REVIEWING',
    'READY_TO_SEAL',
    'REJECTED_ADMISSION',
    'REJECTED_SCOPE',
    'REJECTED_VERIFIER',
    'INDETERMINATE',
    'REJECTED_IMPLEMENTATION',
    'ESCALATED',
];
export const ATTEMPT_PHASES = [
    'CREATED',
    'SPAWNING',
    'SPAWN_FAILED',
    'RUNNING',
    'SETTLED',
    'DISPOSING',
    'DISPOSED',
];
//# sourceMappingURL=types.js.map